apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otel-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "OpenTelemetry Demo Project"
  sourceRepos:
    - "https://open-telemetry.github.io/opentelemetry-helm-charts"
    - "*"
  destinations:
    - namespace: otel-demo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
